import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, Pill, Calendar, User, Clock, HelpCircle, ExternalLink, MessageSquare, Edit, AlertCircle, BookOpen, Activity } from 'lucide-react';
import SafetyBanner from '../components/SafetyBanner';
import ReadAloudButton from '../components/ReadAloudButton';
import ReadableText from '../components/ReadableText';
import ChatBox from '../components/ChatBox';
import { findMedication, getAllConditions, getAllAppointments } from '../utils/dataAccess';
import { getSettings } from '../utils/storage';
import { languageCodes, medicationTranslationTemplates } from '../data/mockData';

export default function MedicationDetails() {
  const { id } = useParams();
  const med = findMedication(id);
  if (!med) return <div className="max-w-3xl mx-auto text-center py-16"><p className="text-slate-500 text-lg mb-4">Medication not found.</p><Link to="/medications" className="btn-primary">Back to Medications</Link></div>;
  const isCurrent = med.status === 'current';
  const language = getSettings().preferredLanguage || 'urdu';
  const relatedCondition = getAllConditions().find(c => c.relatedMedicationIds?.map(String).includes(String(med.id)) || med.reason?.toLowerCase().includes(c.name.toLowerCase()));
  const relatedAppointments = getAllAppointments().filter(a => relatedCondition?.relatedAppointmentIds?.map(String).includes(String(a.id)));

  return <div className="max-w-3xl mx-auto space-y-5"><Link to="/medications" className="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-teal-600 font-medium"><ArrowLeft size={16}/> Back to Medications</Link>
    <div className="card"><div className="flex items-start justify-between gap-4 mb-4"><div className="flex items-center gap-3"><div className={`w-12 h-12 rounded-xl flex items-center justify-center ${isCurrent ? 'bg-teal-100' : 'bg-slate-100'}`}><Pill size={22} className={isCurrent ? 'text-teal-600' : 'text-slate-400'} /></div><div><div className="flex items-center gap-2 mb-1"><span className={`badge ${isCurrent ? 'badge-green' : 'badge-gray'}`}>{med.status}</span><span className="badge badge-teal">{med.type || 'Medicine'}</span></div><h1 className="font-display font-bold text-xl text-slate-800">{med.name}</h1></div></div><ReadAloudButton text={`${med.name}. ${med.explanation || ''}`} languageCode="en-GB" compact /></div>
      <div className="grid sm:grid-cols-2 gap-3">{[{ icon:Pill,label:'Dose',value:med.dose},{icon:Clock,label:'Frequency',value:med.frequency},{icon:Clock,label:'Timing',value:med.timing},{icon:User,label:'Prescriber',value:med.prescriber},{icon:Calendar,label:'Start Date',value:med.startDate ? new Date(med.startDate).toLocaleDateString('en-GB') : 'Not recorded'},...(med.endDate ? [{icon:Calendar,label:'End Date',value:new Date(med.endDate).toLocaleDateString('en-GB')}] : [])].map(({icon:Icon,label,value})=><div key={label} className="bg-slate-50 rounded-lg p-3"><div className="flex items-center gap-2 mb-0.5"><Icon size={13} className="text-slate-400"/><span className="text-xs font-medium text-slate-500">{label}</span></div><p className="text-sm text-slate-700 font-medium pl-5">{value || 'Not recorded'}</p></div>)}</div><div className="mt-3 bg-slate-50 rounded-lg p-3"><p className="text-xs font-medium text-slate-500 mb-0.5">Reason for prescribing</p><p className="text-sm text-slate-700">{med.reason}</p></div></div>
    <div className="card border-teal-200 bg-teal-50/30"><div className="flex items-center gap-2 mb-2"><BookOpen size={16} className="text-teal-600"/><h2 className="font-semibold text-slate-800 text-sm">What is this medicine?</h2><span className="badge badge-teal text-xs">AI Explanation</span></div><ReadableText text={med.explanation} languageCode="en-GB" label="Read English section" compact /><div className="bg-teal-50 border border-teal-100 rounded-lg p-3 mt-3"><p className="text-xs font-medium text-teal-700 mb-1">Translation</p><ReadableText text={(language === 'urdu' && med.explanationUrdu) ? med.explanationUrdu : medicationTranslationTemplates[language]?.(med.name)} languageCode={languageCodes[language]} label="Read translation section" compact textClassName="text-sm text-teal-800 leading-relaxed" /></div></div>
    {relatedCondition && <div className="card"><h2 className="font-semibold mb-3 flex items-center gap-2"><Activity size={16} className="text-green-600"/> Linked condition</h2><Link to={`/conditions/${relatedCondition.id}`} className="block bg-green-50 rounded-lg p-3 text-sm hover:bg-green-100"><b>{relatedCondition.name}</b><br/><span className="text-slate-600">{relatedCondition.summary}</span></Link></div>}
    {relatedAppointments.length > 0 && <div className="card"><h2 className="font-semibold mb-3 flex items-center gap-2"><Calendar size={16} className="text-blue-600"/> Related appointments</h2>{relatedAppointments.map(a => <Link key={a.id} to={`/appointments/${a.id}`} className="block bg-slate-50 rounded-lg p-3 mb-2 text-sm hover:bg-teal-50"><b>{a.title}</b><br/><span className="text-slate-500">{a.date} at {a.time}</span></Link>)}</div>}
    {med.sideEffects?.length > 0 && <div className="card"><div className="flex items-center gap-2 mb-3"><AlertCircle size={16} className="text-amber-500"/><h2 className="font-semibold text-slate-800 text-sm">Common side effects to be aware of</h2></div><div className="mb-3"><ReadAloudButton text={med.sideEffects?.join('. ')} languageCode="en-GB" label="Read side effects" compact /></div><div className="flex flex-wrap gap-2">{med.sideEffects.map(effect => <span key={effect} className="badge badge-yellow">{effect}</span>)}</div><p className="text-xs text-slate-500 mt-2">Speak to your pharmacist or GP if you are worried.</p></div>}
    <div className="card bg-blue-50/50 border-blue-200"><div className="flex items-center justify-between"><div><p className="text-xs font-medium text-blue-700 mb-0.5">Trusted information source</p><p className="text-sm text-blue-800 font-semibold">{med.nhsSource || 'NHS Medicines A to Z placeholder'}</p></div>{med.nhsUrl && <a href={med.nhsUrl} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1 text-xs font-medium text-blue-600 hover:underline">Visit NHS <ExternalLink size={12}/></a>}</div></div>
    <div className="card"><div className="flex items-center gap-2 mb-3"><HelpCircle size={16} className="text-purple-600"/><h2 className="font-semibold text-slate-800 text-sm">Questions to ask your doctor or pharmacist</h2></div><div className="mb-3"><ReadAloudButton text={(med.questions || []).join('. ')} languageCode="en-GB" label="Read questions" compact /></div><ul className="space-y-2">{(med.questions || []).map((q,i)=><li key={i} className="text-sm text-slate-700 bg-purple-50 rounded-lg px-3 py-2 flex items-start gap-2"><HelpCircle size={13} className="text-purple-400 shrink-0 mt-0.5"/>{q}</li>)}</ul></div>
    <SafetyBanner compact /><div><h2 className="font-semibold text-slate-800 text-sm mb-3 flex items-center gap-2"><MessageSquare size={16} className="text-teal-600"/> Ask a question about this medication</h2><ChatBox contextTitle={`your ${med.name} medication`} /></div><Link to={`/medications/${med.id}/edit`} className="btn-secondary text-sm flex items-center gap-2"><Edit size={15}/> Edit Medication</Link>
  </div>;
}
