import { useState } from 'react';
import { languages } from '../data/mockData';
import { getSettings, updateSettings, addNotification } from '../utils/storage';

export default function Settings() {
  const [settings, setSettings] = useState(getSettings());
  const update = (k,v)=>setSettings(p=>({...p,[k]:v}));
  const save = () => { updateSettings(settings); addNotification('Settings updated', 'settings'); alert('Settings saved'); };
  return <div className="max-w-2xl mx-auto space-y-6"><div><h1 className="font-display font-bold text-2xl text-slate-800">Settings</h1><p className="text-sm text-slate-500 mt-1">Choose default language, read-aloud speed, accessibility, and notification preferences.</p></div><div className="card space-y-4"><label className="block"><span className="text-xs font-medium text-slate-600">Preferred explanation language</span><select value={settings.preferredLanguage} onChange={e=>update('preferredLanguage',e.target.value)} className="mt-1 w-full border border-slate-200 rounded-lg px-3 py-2 text-sm">{languages.filter(l=>['urdu','brazilian_portuguese','french','japanese'].includes(l.value)).map(l=><option key={l.value} value={l.value}>{l.label}</option>)}</select></label><label className="block"><span className="text-xs font-medium text-slate-600">Translation style</span><select value={settings.translationStyle} onChange={e=>update('translationStyle',e.target.value)} className="mt-1 w-full border border-slate-200 rounded-lg px-3 py-2 text-sm"><option value="simple">Simple</option><option value="formal">Formal</option><option value="friendly">Friendly family wording</option></select></label><label className="block"><span className="text-xs font-medium text-slate-600">Text-to-speech speed: {settings.speechRate}</span><input type="range" min="0.6" max="1.3" step="0.1" value={settings.speechRate} onChange={e=>update('speechRate',e.target.value)} className="w-full"/></label>{[['largeText','Large text mode'],['highContrast','High contrast mode'],['notifications','Enable notifications']].map(([key,label])=><label key={key} className="flex items-center gap-3"><input type="checkbox" checked={!!settings[key]} onChange={e=>update(key,e.target.checked)} /> <span className="text-sm text-slate-700">{label}</span></label>)}<div className="bg-slate-50 rounded-lg p-3 text-xs text-slate-500">Prototype privacy notice: data is saved in your browser localStorage only. A real app would need secure authentication, encryption, consent, and healthcare data safeguards.</div><button onClick={save} className="btn-primary">Save Settings</button></div></div>;
}
