import { useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, Calendar, Clock, MapPin, User, Building, CheckSquare, HelpCircle, Edit, Download, MessageSquare, FileText, Pill, Activity, Save } from 'lucide-react';
import SafetyBanner from '../components/SafetyBanner';
import ReadAloudButton from '../components/ReadAloudButton';
import ChatBox from '../components/ChatBox';
import { findAppointment, getAllConditions, getAllMedications } from '../utils/dataAccess';
import { KEYS, readStorage, writeStorage, addNotification } from '../utils/storage';

const statusConfig = { upcoming: { label: 'Upcoming', className: 'badge-blue' }, past: { label: 'Past', className: 'badge-gray' }, cancelled: { label: 'Cancelled', className: 'badge-red' } };

export default function AppointmentDetails() {
  const { id } = useParams();
  const appointment = findAppointment(id);
  const [noteType, setNoteType] = useState('before');
  const [notes, setNotes] = useState(() => readStorage(KEYS.appointmentNotes, {})[id] || { before: '', during: '', after: '', questions: '', advice: '', followup: '' });
  if (!appointment) return <div className="max-w-3xl mx-auto text-center py-16"><p className="text-slate-500 text-lg mb-4">Appointment not found.</p><Link to="/appointments" className="btn-primary">Back to Appointments</Link></div>;
  const status = statusConfig[appointment.status] || statusConfig.upcoming;
  const relatedCondition = getAllConditions().find(c => c.relatedAppointmentIds?.map(String).includes(String(appointment.id)));
  const relatedMeds = getAllMedications().filter(m => relatedCondition?.relatedMedicationIds?.map(String).includes(String(m.id)));
  const saveNotes = () => { const all = readStorage(KEYS.appointmentNotes, {}); writeStorage(KEYS.appointmentNotes, { ...all, [id]: notes }); addNotification('Appointment notes saved', 'notes'); };
  const exportCalendar = () => alert('Demo: this would download an .ics calendar file once backend is connected.');

  return <div className="max-w-4xl mx-auto space-y-5"><Link to="/appointments" className="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-teal-600 font-medium"><ArrowLeft size={16}/> Back to Appointments</Link>
    <div className="card"><div className="flex items-start justify-between gap-4 mb-4"><div><div className="flex items-center gap-2 mb-2"><span className={`badge ${status.className}`}>{status.label}</span><span className="badge badge-teal">{appointment.type}</span></div><h1 className="font-display font-bold text-xl text-slate-800">{appointment.title}</h1></div><ReadAloudButton text={`${appointment.title}. ${appointment.notes}`} languageCode="en-GB" compact /></div>
      <div className="grid sm:grid-cols-2 gap-3">{[{icon:Calendar,label:'Date',value:new Date(appointment.date).toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'})},{icon:Clock,label:'Time',value:appointment.time},{icon:Building,label:'Hospital / Clinic',value:appointment.hospital},{icon:User,label:'Doctor',value:appointment.doctor},{icon:Building,label:'Department',value:appointment.department},{icon:MapPin,label:'Address',value:appointment.address}].map(({icon:Icon,label,value})=><div key={label} className="bg-slate-50 rounded-lg p-3"><div className="flex items-center gap-2 mb-0.5"><Icon size={13} className="text-slate-400"/><span className="text-xs font-medium text-slate-500">{label}</span></div><p className="text-sm text-slate-700 font-medium pl-5">{value}</p></div>)}</div></div>
    <div className="card border-teal-200 bg-teal-50/30"><div className="flex items-center gap-2 mb-2"><MessageSquare size={16} className="text-teal-600"/><h2 className="font-semibold text-slate-800 text-sm">What this appointment is for</h2><span className="badge badge-teal text-xs">AI Summary</span></div><p className="text-sm text-slate-700 leading-relaxed mb-3">{appointment.notes}</p><ReadAloudButton text={appointment.notes} languageCode="en-GB" label="Read summary" compact /></div>
    <div className="grid lg:grid-cols-2 gap-4">{relatedCondition && <div className="card"><h2 className="font-semibold mb-3 flex items-center gap-2"><Activity size={16} className="text-green-600"/> Linked condition</h2><Link to={`/conditions/${relatedCondition.id}`} className="block bg-green-50 rounded-lg p-3 text-sm hover:bg-green-100"><b>{relatedCondition.name}</b><br/><span className="text-slate-600">{relatedCondition.summary}</span></Link></div>}{relatedMeds.length > 0 && <div className="card"><h2 className="font-semibold mb-3 flex items-center gap-2"><Pill size={16} className="text-purple-600"/> Related medications</h2>{relatedMeds.map(m => <Link key={m.id} to={`/medications/${m.id}`} className="block bg-slate-50 rounded-lg p-3 mb-2 text-sm hover:bg-teal-50"><b>{m.name}</b> — {m.dose}, {m.frequency}</Link>)}</div>}</div>
    {appointment.preparation.length > 0 && <div className="card"><div className="flex items-center gap-2 mb-3"><CheckSquare size={16} className="text-green-600"/><h2 className="font-semibold text-slate-800 text-sm">How to prepare</h2></div><div className="mb-3"><ReadAloudButton text={appointment.preparation.join('. ')} languageCode="en-GB" label="Read preparation" compact /></div><ul className="space-y-2">{appointment.preparation.map((item,i)=><li key={i} className="flex items-start gap-2.5 text-sm text-slate-700"><div className="w-5 h-5 rounded border-2 border-slate-200 shrink-0 mt-0.5"/>{item}</li>)}</ul></div>}
    {appointment.questions.length > 0 && <div className="card"><div className="flex items-center gap-2 mb-3"><HelpCircle size={16} className="text-purple-600"/><h2 className="font-semibold text-slate-800 text-sm">Questions to ask</h2></div><div className="mb-3"><ReadAloudButton text={appointment.questions.join('. ')} languageCode="en-GB" label="Read questions" compact /></div><ul className="space-y-2">{appointment.questions.map((q,i)=><li key={i} className="text-sm text-slate-700 bg-purple-50 rounded-lg px-3 py-2 flex items-start gap-2"><HelpCircle size={13} className="text-purple-400 shrink-0 mt-0.5"/>{q}</li>)}</ul></div>}
    <div className="card"><div className="flex items-center gap-2 mb-3"><FileText size={16} className="text-blue-600"/><h2 className="font-semibold text-slate-800 text-sm">Appointment Notes</h2></div><div className="flex flex-wrap gap-2 mb-3">{[['before','Before appointment'],['during','During appointment'],['after','After appointment'],['questions','Questions to ask'],['advice','Doctor advice'],['followup','Follow-up actions']].map(([key,label])=><button key={key} onClick={()=>setNoteType(key)} className={`px-3 py-1.5 rounded-full text-xs font-medium ${noteType===key ? 'bg-teal-600 text-white' : 'bg-white border border-slate-200 text-slate-600'}`}>{label}</button>)}</div><textarea value={notes[noteType] || ''} onChange={e=>setNotes(prev=>({...prev,[noteType]:e.target.value}))} rows={5} placeholder="Write appointment notes here..." className="w-full text-sm border border-slate-200 rounded-lg p-3 outline-none focus:border-teal-400"/><button onClick={saveNotes} className="btn-primary mt-3 flex items-center gap-2"><Save size={15}/>Save Notes</button></div>
    <SafetyBanner compact /><div><h2 className="font-semibold text-slate-800 text-sm mb-3 flex items-center gap-2"><MessageSquare size={16} className="text-teal-600"/> Ask a question about this appointment</h2><ChatBox contextTitle={`your ${appointment.title}`} /></div>
    <div className="flex flex-wrap gap-3"><button className="btn-secondary flex items-center gap-2"><Edit size={15}/> Edit Appointment</button><button onClick={exportCalendar} className="btn-secondary flex items-center gap-2"><Download size={15}/> Export to Calendar</button></div>
  </div>;
}
