import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { languages } from '../data/mockData';
import { setUser, updateSettings, addNotification } from '../utils/storage';

export default function Register() {
  const navigate = useNavigate();
  const [form, setForm] = useState({ fullName:'', email:'', password:'', preferredLanguage:'urdu', role:'Family member' });
  const update = (k,v)=>setForm(p=>({...p,[k]:v}));
  const submit = (e)=>{ e.preventDefault(); const user = { fullName: form.fullName, email: form.email, role: form.role, preferredLanguage: form.preferredLanguage }; setUser(user); localStorage.setItem('carebridge_registered_name', form.fullName); updateSettings({ preferredLanguage: form.preferredLanguage }); addNotification('Profile created', 'profile'); window.dispatchEvent(new Event('carebridge-notifications')); navigate('/'); };
  return <div className="max-w-md mx-auto card"><h1 className="font-display font-bold text-2xl text-slate-800 mb-1">Create profile</h1><p className="text-sm text-slate-500 mb-5">Mock registration using localStorage.</p><form onSubmit={submit} className="space-y-4"><label className="block"><span className="text-xs font-medium text-slate-600">Full name</span><input value={form.fullName} onChange={e=>update('fullName',e.target.value)} required className="mt-1 w-full border border-slate-200 rounded-lg px-3 py-2 text-sm"/></label><label className="block"><span className="text-xs font-medium text-slate-600">Email</span><input value={form.email} onChange={e=>update('email',e.target.value)} type="email" required className="mt-1 w-full border border-slate-200 rounded-lg px-3 py-2 text-sm"/></label><label className="block"><span className="text-xs font-medium text-slate-600">Password</span><input value={form.password} onChange={e=>update('password',e.target.value)} type="password" required className="mt-1 w-full border border-slate-200 rounded-lg px-3 py-2 text-sm"/></label><label className="block"><span className="text-xs font-medium text-slate-600">Preferred language</span><select value={form.preferredLanguage} onChange={e=>update('preferredLanguage',e.target.value)} className="mt-1 w-full border border-slate-200 rounded-lg px-3 py-2 text-sm">{languages.filter(l=>['urdu','brazilian_portuguese','french','japanese'].includes(l.value)).map(l=><option key={l.value} value={l.value}>{l.label}</option>)}</select></label><label className="block"><span className="text-xs font-medium text-slate-600">Relationship</span><select value={form.role} onChange={e=>update('role',e.target.value)} className="mt-1 w-full border border-slate-200 rounded-lg px-3 py-2 text-sm"><option>Patient</option><option>Carer</option><option>Family member</option><option>Other</option></select></label><button className="btn-primary w-full">Register</button></form><p className="text-sm text-slate-500 mt-4 text-center">Already have an account? <Link className="text-teal-600 font-semibold" to="/login">Login</Link></p></div>;
}
